### ISSUE TITLE
GERP++ to be included in CellBase and returned within the variant annotation

### ISSUE THREAD

**Issue by javild** [opencb/cellbase#100]
Implement download, build, load and the corresponding code for GERP++ to be returned within the variant annotation

**Comment by imedina** [comment]
It seems that GERP++ is only available for GRCh37. Does make sense to invest some time to implement this for an old assembly version?

**Comment by javild** [comment]
We can leave it in stand by while solving the rest of 3.2.0 issues and wait to see if they release data for GRCh38

**Comment by imedina** [comment]
Moved to v3.3.0 until we decide what to do.

**Comment by javild** [comment]
Move to desired: does not seem to be any plan of releasing data for GRCh38

**Comment by imedina** [comment]
@Swaathik is working in this issue right now, an initial GERP++ parser has been developed at feature/gerp. This includes the downloader and the parser.

**Comment by imedina** [comment]
GERP is now downloaded, built and loaded into MongoDB. Also, Variant annotation also returns GERP scores together with PhastCons and PhyloP
