### ISSUE TITLE
Add GWAS & Cosmic data to WS feature/clinical/all

### ISSUE THREAD

**Issue by aaleman** [opencb/cellbase#107]
The feature/clinical/all WS only returns data from clinvar. It would be great if this WS could return data from GWAS & COSMIC too.

Example URL:
http://wwwdev.ebi.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/clinical/all?include=clinvar&phenotype=Absent%20or%20delayed%20speech%20development

**Comment by javild** [comment]
Done (GWAS will only be available for next CellBase GRCh38 assembly)
