### ISSUE TITLE
Missing gene

### ISSUE THREAD

**Issue by roalva1** [opencb/cellbase#108]
Hello,
I have a gene MDS1 that doesn't get any information from cellbase:
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/id/MDS1-EVI1/xref
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/id/MDS1/xref

However, if you see ensembl, it has a synonymous with MECOM, that it is in cellbase, also EVI
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/id/EVI1/xref
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/id/MECOM/xref

You can see MDS1 here:
http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000085276;r=3:169083499-169663618
I understand that it is a controversial gene name, but should it be in cellbase?

**Comment by imedina** [comment]
This is an interesting point. It seems that synonyms are not retrieved by our scripts using the standard Ensembl API, this could be investigated and easily added to Gene model

**Comment by javild** [comment]
Additional synonyms included during the generation of xrefs. It is now fixed
