### ISSUE TITLE
WS genomic/region/{region}/clinical features source field not exists

### ISSUE THREAD

**Issue by frasator** [opencb/cellbase#111]
Features returned by clinical ws should have a field named 'source' indicating if the feature comes from ClinVar, COSMIC or GWAS

I am using this url:
http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/region/20:32850000-32899999/clinical?of=json

**Comment by imedina** [comment]
frasator is right, this is something important, all mixed objects in a single collection must have a 'source' field to distinguish between them.

**Comment by javild** [comment]
Already reported an tracked by issue #88
