### ISSUE TITLE
Include new population frequencies

### ISSUE THREAD

**Issue by javild** [opencb/cellbase#117]
Include and return within the VariantAnnotation object new population frequencies for:

ExAC, 1000g phase 3, UK10K, GoNL

**Comment by imedina** [comment]
How is the status of this? as fas as I know 1000G Phase 3 is already loaded. What about the others?

**Comment by javild** [comment]
New EVA human dataset will include frequencies for ExAC, UK10K and GoNL as well. This new dataset is expected to by ready by mid-August. As soon as EVA includes these frequencies, they will be extracted and made available to be loaded into CellBase variation collection. As soon as these frequencies are within the variation collection they will be automatically returned by the annotation web service

**Comment by pabarcgar** [comment]
1000 Genome Phase 3 frequencies added. EXAC and UK10K frequencies will be added in the release v4.0.
