### ISSUE TITLE
Gene query does not return results when filtering by biotype

### ISSUE THREAD

**Issue by javild** [opencb/cellbase#126]
http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/gene/all?biotypes=miRNA&limit=3

**Comment by imedina** [comment]
Just remove the 's' from biotypes:

http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/gene/all?biotype=miRNA&limit=3

**Comment by imedina** [comment]
We need to decide and make clear the name of parameters. I think for those parameter that accept more than 1 value names should be plural to make this clear. So in the previous example it should be 'biotypes'. Other single-value parameter such as assembly or limit must remain singular.
