### ISSUE TITLE
To implement a R client

### ISSUE THREAD

**Issue by imedina** [opencb/cellbase#129]
Many bioinformaticians use R as a programming language, it would be very interesting to develop a client R library to could be included in Biocondunctor.
This library will consume REST web services from specified CellBase host. CellBase need to implement Swagger and data model schemas calls in order to R client to discover new functionality.

**Comment by javild** [comment]
First package ready on branch feature/R. Still working on Reference Manual and Vignette

**Comment by javild** [comment]
First approach ready on develop branch. Also submitted to Bioconductor
