### ISSUE TITLE
Empty response when calling genomic/chromosome/all?assembly=GRCh38

### ISSUE THREAD

**Issue by frasator** [opencb/cellbase#136]
Removing the assembly query param works.
Don't know if this should return empty intentionally or is a bug.
All the assemblies from a species have the same chromosomes?

http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/chromosome/all?assembly=GRCh38

**Comment by frasator** [comment]
More web services with this issue

http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/region/1:124624600-124624699,1:124624700-124624799/sequence?assembly=GRCh38

http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/chromosome/1/info?assembly=GRCh38

**Comment by javild** [comment]
GRCh38 is not yet loaded. We are currently working on it.
