### ISSUE TITLE
Include response type in REST web services

### ISSUE THREAD

**Issue by dmontaner** [opencb/cellbase#143]
Each web service returns a JSON structure that may be of class gene, snp, exon... 
Once the _class type_ is known we can go to its corresponding _model_ method
and find out all information that may be available in the result of the query __before__ executing it.

For instance the output of the `feaurte/gene/{geneId}/info` is of the _type_ `gene`
and is described in the `feature/gene/model` web service.
The output of the `feaurte/gene/{geneId}/snp` is of _type_ `snp` and its structure must be found in the
`feature/snp/model` web service. 

It would be useful to be able to know the _type_ of the query before sending it so that it is known which output is expected.

**Comment by imedina** [comment]
This has been implemented as expected
