### ISSUE TITLE
exclude in full_annotation

### ISSUE THREAD

**Issue by Antonior26** [opencb/cellbase#147]
You can not perform exclude/includes in the full_annotation ws for variants, at least exclude is essential.

e.g:
http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/gene/first?include=chromosome,start,end&assembly=GRCh37&exclude=transcripts

**Comment by imedina** [comment]
I have implemented both include/exclude and seems to be working in my tests. The annotators to include/exclude are: ["clinical", "conservation", "consequenceType", "expression", "drugInteraction", "populationFrequencies"]
