### ISSUE TITLE
Include/exclude queryparams do not work

### ISSUE THREAD

**Issue by aaleman** [opencb/cellbase#148]
I am using include/exclude queryparams to include/exclude fields and they do not work.
The WS always returns all fields

Example URL: 
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/variant/11:92085623:C:T/full_annotation?exclude=consequenceTypes
http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/variant/11:92085623:C:T/full_annotation?exclude=consequenceTypes

Related #106

**Comment by imedina** [comment]
Thanks for reporting. Some of them seem to work properly such as 'populationFrequencies' or 'conservationScores' but not 'consequenceTypes'. This must be implemented.

**Comment by imedina** [comment]
This has been fixed (and improved) in #147 
It will be pushed to bioinfodev this in a couple of days

**Comment by javild** [comment]
Solved at #69
