### ISSUE TITLE
Redundant files?

### ISSUE THREAD

**Issue by dmontaner** [opencb/cellbase#149]
Files:

cellbase-server/src/main/java/org/opencb/cellbase/server/ws/genomic/VariantWSServer.java

cellbase-server/src/main/java/org/opencb/cellbase/server/ws/genomic/VariationAnnotationWSServer.java

have the same @Path("/{version}/{species}/genomic/variant") parameter

One file seems to be an old version... it may be better to clear it up.

**Comment by javild** [comment]
Done. Only VariantWSServer.java remains
