### ISSUE TITLE
Modify gene collection schema

### ISSUE THREAD

**Issue by javild** [opencb/cellbase#155]
Core gene attributes (e.g. chr, start, end, transcripts, exons, ...) will remain in current gene (core) collection. Create a new collection for extra annotation features: expression, dgidb, etc.

**Comment by imedina** [comment]
We have finally solved this by adding a new _annotation_ field in Gene model, this contains expression, drugs and new disease data, see opencb/biodata@f8463c09d8729746cb478e0d62e386dd86727727
