### ISSUE TITLE
Update configuration.json file

### ISSUE THREAD

**Issue by imedina** [opencb/cellbase#164]
We need to upgrade the species section and Ensembl version for next release v4. Ensembl 82 will be used in v4.

**Comment by imedina** [comment]
Also, both installations at University of cambrdige and EBI must be updated

**Comment by mbsimonovic** [comment]
hey guys, there might've been some data format changes between v79 and v81, gtf for example https://github.com/opencb/cellbase/issues/144, but possibly others. do you maybe have some tests to check for this?
