### ISSUE TITLE
Cosmic and GWAS need to be returned when queried by Gene

### ISSUE THREAD

**Issue by imedina** [opencb/cellbase#170]
Currently querying by region returns all clinical variants, but when querying by gene only ClinVar is returned. Example:

http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/gene/BRCA2/clinical?limit=1

http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/region/13%3A32889611-32973805/clinical?limit=1

**Comment by javild** [comment]
Solved now:

http://bioinfodev.hpc.cam.ac.uk/cellbase-dev-v4.0/webservices/rest/latest/hsapiens/feature/gene/BRCA2/clinical?limit=3&source=cosmic

http://bioinfodev.hpc.cam.ac.uk/cellbase-dev-v4.0/webservices/rest/latest/hsapiens/feature/gene/BRCA2/clinical?limit=3&source=clinvar

http://bioinfodev.hpc.cam.ac.uk/cellbase-dev-v4.0/webservices/rest/latest/hsapiens/feature/gene/BRCA2/clinical?limit=3
