### ISSUE TITLE
Error loading data to mongo - no index found

### ISSUE THREAD

**Issue by jpdna** [opencb/cellbase#184]
(I sent an email about this last weel but I didn't then create an issue here in github.)

When loading to mongo following the standard instructions:

```
./cellbase.sh load --data genome --database cellbase_hsapiens_grch37_v3 --input ../../../test_genome_build_grch37/ --num-threads 8
```

( using develop branch cloned Nov 25th)
the error below is seen:
./cellbase.sh load --data genome --database cellbase_hsapiens_grch37_v3 --input ../../../test_genome_build_grch37/ --num-threads 8
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 1 records read from '../../../test_genome_build_grch37/genome_info.json'
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - All the '1' records have been loaded into the database
[main] INFO org.opencb.datastore.mongodb.MongoDataStore - MongoDataStore: connection closed
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 1549969 records read from '../../../test_genome_build_grch37/genome_sequence.json.gz'
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - All the '1549969' records have been loaded into the database
[main] INFO org.opencb.datastore.mongodb.MongoDataStore - MongoDataStore: connection closed
[main] ERROR org.opencb.cellbase.mongodb.loader.MongoDBCellBaseLoader - No path can be provided for index, check index folder 'null' and data 'genome_sequence'
[main] WARN org.opencb.cellbase.mongodb.loader.MongoDBCellBaseLoader - No index found for 'genome_sequence'

The problem appears to be that the mongo javascript index files cannot be found by the loading code.
I was able to fix this in a hack hardcoding way in constructor of MongoDBCellBaseLoader, but a proper fix needs to be made still:

My hack:
public MongoDBCellBaseLoader(BlockingQueue<List<String>> queue, String data, String database,
                             CellBaseConfiguration cellBaseConfiguration) {
    super(queue, data, database, cellBaseConfiguration);
     indexScriptFolder = Paths.get("/home/paschall/OpenCB/nov11/cellbase/cellbase-app/app/mongodb-scripts");
    //if(cellBaseConfiguration.getDatabase().getOptions().get("mongodb-index-folder") != null) {
    //   indexScriptFolder = Paths.get(cellBaseConfiguration.getDatabase().getOptions().get("mongodb-index-folder"));
   // }
}

**Comment by javild** [comment]
A dynamic parameter can be specified through the command line to specify the path where the .js that create the indexes are stored: -Dmongodb-index-folder. For example:

./cellbase.sh load -d clinical --database cellbase_hsapiens_grch37_v3 -i ~/tmp/cellbasedata/homo_sapiens_grch37/mongodb/ -L debug -Dmongodb-index-folder=/home/fjlopez/appl/cellbase/cellbase-app/app/mongodb-scripts/

**Comment by jpdna** [comment]
This parameter option is good to know, but it seems like this will still be a problem for users trying to follow the instructions to install?  Will it be clear from documentation that users need to include this in -Dmongodb-index-folder parameter?  Can it not be made to build by default in a way that doesn't require user to add this?
