### ISSUE TITLE
Errror downloading ensembl variation files

### ISSUE THREAD

**Issue by jpdna** [opencb/cellbase#186]
(on develop branch cloned Nov 25)

Running:
 ./cellbase.sh download -d all --output ../../../nov25_homo_GRCh37/ 

The looked for FTP files dont exist:

Get errors like:
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/variation.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/variation_feature.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/transcript_variation.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/variation_synonym.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/seq_region.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/source.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/attrib.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/attrib_type.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/seq_region.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/structural_variation_feature.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/study.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/phenotype.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/phenotype_feature.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/phenotype_feature_attrib.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/motif_feature_variation.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/genotype_code.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/allele_code.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/population_genotype.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/population.txt.gz cannot be downloaded
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - Error executing wget, error code: 8. More info in log file: null
[main] WARN class org.opencb.cellbase.app.cli.DownloadCommandExecutor - ftp://ftp.ensembl.org/pub/release-82/mysql/homo_sapiens_variation_82_37/allele.txt.gz cannot be downloaded

**Comment by javild** [comment]
Unfortunately, ENSEMBL-82 ftp paths for GRCh37 seem not to follow previous structure

**Comment by Philip-Wu** [comment]
I also had the same error for GCh37. To fix this you can modify your configuration.json file such that

ensemblVersion is changed from "82_37" to "75_37". Ensembl release 75 is the last known version to support GRCh37.

`[
			{
				"id":"hsapiens",
				"scientificName":"Homo sapiens",
				"assemblies":[
					{
						"ensemblVersion":"75_37",
						"name":"GRCh37"
					},
					{
						"ensemblVersion":"82_38",
						"name":"GRCh38"
					}
				]`

It would be good if this could be updated in the source as well.

**Comment by javild** [comment]
As @Philip-Wu commented e82 is not really a GRCh37 proper version but a GRCh38. Thus, building the e82 GRCh37 is a bit trickier and requires manual search and download of the corresponding ENSEMBL 82 GRCh37 files. Alternatively you can downgrade the ENSEMBL version to use.

Anyway, as indicated in the GitHub wiki, you can download already built human data models from our servers - there is no need for you to build the human data models from scratch which can be a bit painful and time consuming:

http://bioinfo.hpc.cam.ac.uk/downloads/cellbase/v4/homo_sapiens_grch37/mongodb/
