### ISSUE TITLE
Create public FTP site for GRCh37 JSON file download

### ISSUE THREAD

**Issue by jpdna2** [opencb/cellbase#195]
Setting a public FTP server with the JSON files would be interesting.

**Comment by imedina** [comment]
All source and built JSON files can be downloaded from here for all versions:

http://bioinfo.hpc.cam.ac.uk/downloads/cellbase/

**Comment by mbsimonovic** [comment]
hey guys, which ensembl release is v3 based on, 79 maybe? when did you make it, recently or last year?
