### ISSUE TITLE
TranscriptMongoDBAdaptor count method should count transcritpts not genes

### ISSUE THREAD

**Issue by imedina** [opencb/cellbase#198]
Current implementation is counting the number of genes instead of the number of transcripts, an aggregation using $unwind and a $match could solve the problem.

**Comment by javild** [comment]
Done.
For example:
http://bioinfodev.hpc.cam.ac.uk/cellbase-dev-v4.0/webservices/rest/v4/hsapiens/feature/transcript/count?xrefs=BRCA2
