### ISSUE TITLE
ConsequenceType should include position,reference,alternative for stop_gained and non-uniprot variants

### ISSUE THREAD

**Issue by mattdmem** [opencb/cellbase#203]
Currently proteinVariantAnnotation is only returned if the variant is in uniprot etc (well this is what antonio tells me).  The problem is, if it's not in there or the mutation is stop_gained then we do not get reference, position, and alternative for that transcript/protein.  For stop gained for example it would be nice to have, for example reference=ARG, position=100, alternative=TER.

**Comment by javild** [comment]
Thanks for your comment.

It does not have to do with the fact of the variant being in UniProt. Most probably has to do with certain coding consequence types for which we are simply not providing the proteinVariantAnnotation object, and also probably indels are not being properly annotated with the proteinVariantAnnotation object either. This has to be fixed. We'll check it out and fix it.

**Comment by mattdmem** [comment]
Great thanks... Especially cases where it's a stop gained - I would expect something like Q61*

**Comment by javild** [comment]
Fixed for stop_gained variants:

http://bioinfodev.hpc.cam.ac.uk/cellbase-dev-v4.0/webservices/rest/v4/hsapiens/genomic/variant/22:16287261:G:A/annotation

Insertions and deletions remain to be fixed

**Comment by mattdmem** [comment]
Thanks Javier!

**Comment by javild** [comment]
Now ready for insertions and deletions;:

http://bioinfodev.hpc.cam.ac.uk/cellbase-dev-v4.0/webservices/rest/v4/hsapiens/genomic/variant/13:52718051:-:T/annotation

http://bioinfodev.hpc.cam.ac.uk/cellbase-dev-v4.0/webservices/rest/v4/hsapiens/genomic/variant/18:30913143:T:-/annotation
