### ISSUE TITLE
Add DOCM to annotation

### ISSUE THREAD

**Issue by mattdmem** [opencb/cellbase#207]
http://docm.genome.wustl.edu

**Comment by javild** [comment]
It would be nice to know how much this dataset overlaps with ClinVar, COSMIC or GWAS catalog, did you have the chance to check? 
The downloadable data is a VCF with 712 variants and not much data, I guess that is the total number of variants they currently have, right?
I can see more valuable data in the json provided by the "Variant Detail Endpoint":
http://docm.genome.wustl.edu/api/v1/variants/ENST00000389048:c.3586C%3EA.json
but unfortunately can only be queried by the hgvs. Would it be an option to write the authors to get just one json file with this detailed data?

**Comment by mattdmem** [comment]
It's the drug data we are most interested in - which is not in clinvar.  Our idea was to annotate VCF with cell base which gets us hgvs and then query the api to get a all the data in a structure that would be amenable to cell base

"drug_interactions": [
    {
      "drug": "PI3K pathway inhibitors + MEK inhibitors",
      "pathway": "activation",
      "effect": "gain-of-function",
      "association": "response",
      "status": "preclinical",
      "evidence_type": "emerging",
      "source_pubmed_id": ​22733540,
      "aggregated_by": "Dienstman Knowledge Database - https://www.synapse.org/#!Synapse:syn2370773"
    }

**Comment by javild** [comment]
Done.
https://github.com/opencb/cellbase/commit/4a630d0942796df7cea460c8e5707abe1cd72f5b
