### ISSUE TITLE
Population frequencies web services must return all frequencies

### ISSUE THREAD

**Issue by imedina** [opencb/cellbase#22]
When querying population frequencies like:
http://wwwdev.ebi.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/region/3:1166675-1166675/snp

Only frequencies different from '1' are returned. MongoDB has to contain only those.

**Comment by pabarcgar** [comment]
What if a Variation has no frequency for none of the 1000 Genomes populations? Variation parser should output 1 as reference frequency for all the 1000 Genomes superpopulations?

**Comment by imedina** [comment]
No, only in those cases where 1000G_ALL exists, if there is not any frequencies then it is unknown

**Comment by imedina** [comment]
This is done
