### ISSUE TITLE
Links in wiki do not work

### ISSUE THREAD

**Issue by jhagberg** [opencb/cellbase#224]
The links in the wiki page:
https://github.com/opencb/cellbase/wiki/Load-Data-Models
do not work
it should be 
http://bioinfo.hpc.cam.ac.uk/downloads/cellbase

**Comment by javild** [comment]
Thanks for your comment.
You are right. Indeed, installation documentation must be updated. I just marked it as deprecated and will update it as soon as possible. We are working on it.
Sorry for the inconvenience this might cause.

**Comment by javild** [comment]
Following sections: 
  * Download Sources
  * Build Data Models
  * Load Data Models
were updated and links fixed
