### ISSUE TITLE
Add bacteria species

### ISSUE THREAD

**Issue by imedina** [opencb/cellbase#244]
There is the need for some bacteria species in CelBase, some of the requested or interesting bacteria include:
- Mycoplasma pneumoniae M129
- E. coli

others?

**Comment by mikegoodstadt** [comment]
Hola! Any news on this?

**Comment by javild** [comment]
Not yet I'm afraid...

**Comment by javild** [comment]
Ready on development servers:

http://bioinfodev.hpc.cam.ac.uk/cellbase-4.5.0-rc/webservices/rest/latest/mpneumoniae/feature/gene/search?limit=3&skip=-1&count=false&Output%20format=json

http://bioinfodev.hpc.cam.ac.uk/cellbase-4.5.0-rc/webservices/rest/latest/ecoli/genomic/region/Chromosome%3A333-3333/sequence?limit=-1&skip=-1&count=false&Output%20format=json&strand=1

Please note that integrated data is currently restricted to ENSEMBL provided data, meaning essentially genome sequences, protein sequences and genome annotation, i.e. basically "Gene" section and "Region" -> /region/<region-string>/sequence methods
