### ISSUE TITLE
Number of annotations written for last batch of variants is not echoed to standard error

### ISSUE THREAD

**Issue by katherinesmith** [opencb/cellbase#249]
The number of input variants in the VCF is the same as the number of lines in the cellbase JSON output. However, the last number of reported annotations (e.g. ` [pool-1-thread-5] INFO org.opencb.biodata.formats.variant.annotation.io.JsonAnnotationWriter - 8096118 written annotations.`) is usually slightly smaller than this number, although occasionally it is the same.

**Comment by javild** [comment]
Fixed. Total number of written variants is now properly reported to the standard output before the variant-annotation execution finished.

Required a minor fix at biodata JsonAnnotationWriter
