### ISSUE TITLE
drerio: error downloading all_gene_disease_associations.txt.gz

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/cellbase#258]
branch develop:
[all_gene_disease_associations.txt.gz](http://www.disgenet.org/ds/DisGeNET/results/all_gene_disease_associations.txt.gz)  doesn't exist but
[all_gene_disease_associations.tsv.gz](http://www.disgenet.org/ds/DisGeNET/results/all_gene_disease_associations.tsv.gz) does, but seems like it's got a slightly different format: 
```# geneId  geneName        description     diseaseId       diseaseName     score   NofPmids        NofSnps sources```
so doesn't have geneSymbol but has NofSnps

**Comment by javild** [comment]
Fixed - gene disease associations are not downloaded now for Danio Rerio. In addition. for each species only data types available for it will be downloaded-built-loaded
