### ISSUE TITLE
Consequence Type calculation

### ISSUE THREAD

**Issue by imedina** [opencb/cellbase#26]
A new method is needed to calculate the consequence type from SNV variants. This will be part of the Variant Annotation new functionality.
The behaviour must be as similar as Ensembl VEP as possible

**Comment by javild** [comment]
Variant annotation functionality ready:

http://wwwdev.ebi.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/variant/19:45411941:T:C/full_annotation
