### ISSUE TITLE
New Variant Annotation functionality

### ISSUE THREAD

**Issue by imedina** [opencb/cellbase#27]
New variant annotation functionality can be implemented, this will return all the known information about a variant in CellBase: consequence type #26 , conservation, ...
Data models must be added to biodata-models.

**Comment by javild** [comment]
Variant annotation functionality ready:

http://wwwdev.ebi.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/variant/19:45411941:T:C/full_annotation
