### ISSUE TITLE
Error at building

### ISSUE THREAD

**Issue by apaytuvi** [opencb/cellbase#274]
I have the following error at building:

`[ERROR] Failed to execute goal on project cellbase-app: Could not resolve dependencies for project org.opencb.cellbase:cellbase-app:jar:4.0.0-rc: Failed to collect dependencies at psidev.psi.mi:psimitab:jar:1.8.5: Failed to read artifact descriptor for psidev.psi.mi:psimitab:jar:1.8.5: Could not transfer artifact psidev.psi.mi:psimitab:pom:1.8.5 from/to intact.nexus (http://www.ebi.ac.uk/intact/maven/nexus/content/groups/public): Failed to transfer file: http://www.ebi.ac.uk/intact/maven/nexus/content/groups/public/psidev/psi/mi/psimitab/1.8.5/psimitab-1.8.5.pom. Return code is: 500 , ReasonPhrase:Internal Server Error. -> [Help 1]`

**Comment by javild** [comment]
Thanks for your comment

Yes indeed we are aware - EBI servers are down and the psimitab dependency cannot be downloaded. It has been failing now for more than two days and a number of users have already complained, so we have decided to temporarily remove that dependency (_develop_ branch) since it's not critical for most of the CellBase functioning. Please pull from develop and try again

**Comment by javild** [comment]
Finally decided to temporarily remove the dependency from the release/v4.0.0 branch as well - will be enabled again as soon as the EBI servers are up. Again, this dependency is not critical for most of the CellBase functioning.

Please pull from release/v4.0.0 and compile again

**Comment by apaytuvi** [comment]
@javild 

I've pulled from release/v4.0.0 and:

`[ERROR] Plugin org.codehaus.gmaven:gmaven-plugin:1.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.gmaven:gmaven-plugin:jar:1.5: Could not transfer artifact org.codehaus.gmaven:gmaven-plugin:pom:1.5 from/to central (https://repo.maven.apache.org/maven2): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`

**Comment by javild** [comment]
@apaytuvi 

We have not been notified about anyone else getting that error and I can't manage to reproduce it. Could you please give more details about the specific steps/commands you have run?
You can also try to clear your ~/.m2/repository/ directory and start compiling from scratch again.
