### ISSUE TITLE
Bug in filtering gene by id

### ISSUE THREAD

**Issue by Swaathik** [opencb/cellbase#276]
When searching genes by id, the query result returns an empty result. 

Example:
http://bioinfodev.hpc.cam.ac.uk/cellbase-4.5.0-beta/webservices/rest/latest/hsapiens/feature/gene/search?limit=-1&skip=-1&count=false&Output%20format=json&id=ENST00000380152

The above id is a valid Id but the result is empty.

**Comment by javild** [comment]
The id parameter of the gene/search web services will filter by ENSEMBL **gene** id. Is not really a bug but an error on the example shown by the Swagger documentation. The example has been fixed.

Only valid ENSEMBL gene ids shall be used for that parameter and therefore the empty result returned when searching by ENSEMBL **transcript** id is correct
