### ISSUE TITLE
Include repeats regions into Cellbase

### ISSUE THREAD

**Issue by mermegar** [opencb/cellbase#289]
Have information about repeated sequences may be interesting.

**Comment by javild** [comment]
New web service added to query repeats by region:
https://github.com/opencb/cellbase/commit/f6cbb30ced6bc7c61aa1ba7777a676957ec99c84

Repeats were also added to variant annotation some commits ago, more info at:
https://github.com/opencb/cellbase/issues/318
https://github.com/opencb/cellbase/issues/317
https://github.com/opencb/cellbase/issues/316
