### ISSUE TITLE
Missed annotations in ".../variant/{variants}/annotation" reply

### ISSUE THREAD

**Issue by dnafault** [opencb/cellbase#296]
For some reason, call to [1] doesn't return all the annotations for a given variant, e.g. it doesn't return all the "consequenceTypes" and "conservation" annotations. These annotations do exist in variation collection in database for that particular variants. Tried v4.0.0 and v4.5.0-beta.1. We can see these annotations in reply from [2] though.

[1] <host>/cellbase/webservices/rest/v4/hsapiens/genomic/variant/{variants}/annotation
[2] http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v4/hsapiens/genomic/variant/{variants}/annotation

**Comment by dnafault** [comment]
Please close the ticket, we've solved the issue.

**Comment by imedina** [comment]
Thanks.
