### ISSUE TITLE
allow filter by annotationFlag in gene/tx queries

### ISSUE THREAD

**Issue by Antonior26** [opencb/cellbase#300]
The below url doesn't work, would be great if we can have this ability

{host}/webservices/rest/v4/hsapiens/feature/gene/ZNF563/info?assembly=GRch37&transcripts.annotationFlags=basic

**Comment by javild** [comment]
Done:

http://bioinfodev.hpc.cam.ac.uk/cellbase-4.5.0-rc/webservices/rest/v4/hsapiens/feature/gene/BRCA2/info?transcripts.annotationFlags=basic
