### ISSUE TITLE
Index and annotate non human VCFs

### ISSUE THREAD

**Issue by apaytuvi** [opencb/cellbase#303]
Is there the possibility to index and annotate VCF variants of non-human species?

Thank you.

**Comment by javild** [comment]
I'd need you to clarify what you mean with "index" a VCF.

Regarding the annotation the answer is yes. The variant annotator implementation runs regardless of the species data being stored in the database. Obviously, you will need to properly populate a CellBase database with the data for the corresponding species; the more data you are able to load in the database (core annotation, gene expression, genome conservation scores, etc.), the more annotation will be available for your species - you are not expected to find clinical data for the Tomato, for example, but that shall not represent a problem.

**Comment by javild** [comment]
This issue has been inactive for a number of days. Closing it. May be reopened if necessary
