### ISSUE TITLE
Please include the new ENSR regulatory annotations into Cellbase

### ISSUE THREAD

**Issue by emmarath** [opencb/cellbase#306]
Cellbase does not have the new ENSR regulatory annotations. VEP86 does have them. They seem to be very informative for the tricky and important area of non-coding DNA analysis. 
Details at http://asia.ensembl.org/info/genome/funcgen/regulatory_build.html 
Some examples:
13,19411257,G,T,ENSR00001638368,,open_chromatin_region,regulatory_region_variant,,
13,19411352,A,G,ENSR00001638368,,open_chromatin_region,regulatory_region_variant
13,19495468,G,A,ENSR00000274087,,TF_binding_site,regulatory_region_variant
13,19495501,A,G,ENSR00000274087,,TF_binding_site,regulatory_region_variant
13,19495639,G,A,ENSR00000274087,,TF_binding_site,regulatory_region_variant,
13,19495645,G,A,ENSR00000274087,,TF_binding_site,regulatory_region_variant
13,19663795,A,G,ENSR00001638369,,TF_binding_site,regulatory_region_variant
13,19692302,A,G,ENSR00000274090,,open_chromatin_region,regulatory_region_variant
13,19728346,C,T,ENSR00000054191,,TF_binding_site,regulatory_region_variant,,
13,19728346,C,T,ENSR00001638370,,CTCF_binding_site,regulatory_region_variant
13,19920518,C,T,ENSR00001638371,,CTCF_binding_site,regulatory_region_variant
13,20013276,C,T,ENSR00001507591,,TF_binding_site,regulatory_region_variant,,
13,20013276,C,T,ENSR00001638372,,CTCF_binding_site,regulatory_region_variant
13,20133455,A,C,ENSR00001638373,,enhancer,regulatory_region_variant
13,20133566,C,G,ENSR00001638373,,enhancer,regulatory_region_variant
13,20138645,C,T,ENSR00000512493,,promoter,regulatory_region_variant
13,20138930,A,G,ENSR00000512493,,promoter,regulatory_region_variant
13,20735237,G,A,,MA0162.2,,,TF_binding_site_variant,,
13,20735237,G,A,,PB0010.1,,,TF_binding_site_variant
13,25180151,C,T,,ENSR00001638817,,CTCF_binding_site,regulatory_region_variant,,
13,25180151,C,T,,MA0139.1,,,TF_binding_site_variant,

**Comment by javild** [comment]
Hi @emmarath, thanks for your comment. We'll check that out and include the ENSR ids in future versions of the annnotator.

**Comment by javild** [comment]
Code is now ready. 
Will be returned (for assembly GRCh38) as soon as database is updated to e89 GRCh38
