### ISSUE TITLE
gene_extra_info.pl fails for yeast

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/cellbase#309]
Master branch (4.5-rc), gene_extra_info.pl fails for yeast because L154 returns undefined so L155 fails because get_all_synonyms is called on undefined. 

Steps to reproduce:

`perl ./bin/ensembl-scripts/gene_extra_info.pl --verbose --species "Saccharomyces cerevisiae" --outdir saccharomyces_cerevisiae_r64-1-1/gene --ensembl-libs /opt/ensembl --phylo no-vertebrate`

 $gene->stable_id is "15S_rRNA"

**Comment by javild** [comment]
Thanks for reporting this issue @mbsimonovic 

I'll check it out
