### ISSUE TITLE
Reimplement parsers to follow a more general ETL model

### ISSUE THREAD

**Issue by javild** [opencb/cellbase#31]
Some parsers will be reimplemented so that they generate a general data model stored in a json object. 'Loaders' will be implemented which will transform data into an appropriate an efficient format for the specific DBMS (e.g. MongoDB), as well as will  load them into the DB. The objective is to obtain a data model which contains all the information regardless of the specific implementation for a given DBMS.

**Comment by imedina** [comment]
This has been implemented in v3.1.0. Moving this to closed release
