### ISSUE TITLE
Include GRCh37 allele frequencies from DiscovEHR

### ISSUE THREAD

**Issue by katherinesmith** [opencb/cellbase#315]
This is an exome sequencing study of 50,726 individuals, including some with diseases. Variants with AF <0.001 are indicated with the INFO tag AF_LT_001 rather than an exact frequency

http://discovehrshare.com/downloads

**Comment by javild** [comment]
Great, this task requires the following steps:
- [ ] Check biodata is able to parse that frequency format
- [ ] Load into OpenCGA installation
- [ ] Export parsed frequencies from OpenCGA installation
- [ ] Annotate CellBase-variation with updated frequencies
- [ ] Replace current CellBase-variation by the new CellBase-variation with updated frequencies

**Comment by javild** [comment]
Done.
