### ISSUE TITLE
HTTP 504 Gateway Time-out

### ISSUE THREAD

**Issue by mh11** [opencb/cellbase#319]
I tried to annotate a VCF file using the cellbase API and it failed due to a time-out. The steps I took were:
 - download latest version from here: https://github.com/opencb/cellbase/releases (cellbase-4.5.0-rc.tar.gz)
 - tar xzf cellbase-4.5.0-rc.tar.gz
 - ./cellbase-4.5.0-rc/bin/cellbase.sh variant-annotation -a GRCh37 -o my-annot -s hsapiens -i my.vcf

then I got the error message:

```
 WARN  VariantClient:257 - CellBase REST fail. Error parsing query result for ids 1:66365:-:TA,... hosts: http://bioinfo.hpc.cam.ac.uk:80/cellbase, version: v4, category: genomic, subcategory: variant, resource: annotation, queryOptions: {"useCache":true,"phased":false,"limit":1000}. Exception message: HTTP 504 Gateway Time-out
```

**Comment by javild** [comment]
Hi @mh11 
It seems to be working fine for me now. Maybe a temporary fail occurred? Would you please re-check?
Many thanks

**Comment by javild** [comment]
Closing ticket. May be reopened if needed.
