### ISSUE TITLE
Include GRCh37 allele frequencies from GnoMAD

### ISSUE THREAD

**Issue by katherinesmith** [opencb/cellbase#321]
This database is the successor to ExAC. It contains exome sequence data from 123,126 individuals and whole genome sequencing from 15,496 individuals.

http://gnomad.broadinstitute.org/downloads

https://macarthurlab.org/2017/02/27/the-genome-aggregation-database-gnomad/

**Comment by javild** [comment]
Great, this task requires the following steps:
- [ ] Load into OpenCGA installation
- [ ] Export parsed frequencies from OpenCGA installation
- [ ] Annotate CellBase-variation with updated frequencies
- [ ] Replace current CellBase-variation by the new CellBase-variation with updated frequencies

**Comment by j-coll** [comment]
Hi @katherinesmith ,

I have seen that the genomAD dataset has defined 11 cohorts:
 - 1 cohort with ALL samples
 - 7 populations [AFR, AMR, ASJ, EAS, FIN, NFE, OTH]
 - 2 cohorts for Male, Female
 - 1 cohort with _raw_ data, "before filtering low-confidence genotypes"

For sure we are going to ingest the data of ALL and the 7 populations.

Are we interested in Male/Female and _raw_ data?

**Comment by j-coll** [comment]
Another question is, in case that we are interested on Male/Female cohorts, should we respect the case [`Male`, `Female`] or use capital letters [`MALE`, `FEMALE`]?

**Comment by katherinesmith** [comment]
Hi @j-coll, I think that the raw, Male and Female cohorts might be nice to have at some point, but they aren't essential and I don't think we would use them anytime soon. So if it's going to be a lot of work to include them and you have other things to do then it's probably not worth the time right now. If they are included, then I'm not personally bothered how they are capitalised.

INFO/Hemi lists the count of hemizygous individuals on the X, so it's not necessary to infer this from sex-specific counts.

**Comment by katherinesmith** [comment]
You've most likely already discovered that whereas the ExAC VCF has INFO fields for heterozygous genotype counts, gnomAD has INFO/GC, a comma-separated list of genotype counts. It would be great to include genotype frequencies in Cellbase for gnomAD as is done for ExAC, and also to include the hemizygous variant frequency on the X if this isn't a huge additional amount of work.

**Comment by imedina** [comment]
Just leaving here what I commented privately to @j-coll 

I would focus on ALL, AFR, AMR, ASJ, EAS, FIN, NFE, OTH. I do not think male, female or raw are interesting or needed right now, and the can be added at any time in the future.

**Comment by j-coll** [comment]
In the chromosome X, for each population, we have this information:
```
AC_AFR
AC_AFR_Female
AC_AFR_Male

AF_AFR
AF_AFR_Female
AF_AFR_Male

AN_AFR
AN_AFR_Female
AN_AFR_Male

GC_AFR_Female
GC_AFR_Male
Hemi_AFR
Hom_AFR
```
But, is not possible to use the INFO/Hemi for the genotype frequencies because the value is always missing (dot).

It's possible to extract the allele frequencies with the existing code, and if the INFO/Hemi tag was correct, it would be possible to get the genotype frequencies too. But with the GC split in male/female counts, we will need to make some ad-hoc code for this.

**Comment by j-coll** [comment]
https://github.com/opencb/biodata/commit/2537f79170aa5ae7e5d9346f046021be615706c2

**Comment by javild** [comment]
Done
