### ISSUE TITLE
Include GRCh38 allele frequencies from ESP6500

### ISSUE THREAD

**Issue by katherinesmith** [opencb/cellbase#323]
These frequencies are available in GRCh37 cellbase as study: "ESP_6500" and population: "European_American" or population: "African_American". Since GRCh38 frequencies are available, it would be great to have these in Cellbase.

Official liftover:

http://evs.gs.washington.edu/evs_bulk_data/ESP6500SI-V2-SSA137.GRCh38-liftover.snps_indels.vcf.tar.gz

In this VCF, CHR and POS are still GRCh37; the INFO field GRCh38_POSITION indicates GRCh38 coordinates. So it would probably be more convenient to use the Ensembl version:

ftp://ftp.ensembl.org/pub/release-86/variation/vcf/homo_sapiens/ESP6500-African_American.vcf.gz
ftp://ftp.ensembl.org/pub/release-86/variation/vcf/homo_sapiens/ESP6500-European_American.vcf.gz

**Comment by javild** [comment]
Great, this task requires the following steps:
- [ ] Load into OpenCGA installation
- [ ] Export parsed frequencies from OpenCGA installation
- [ ] Annotate CellBase-variation with updated frequencies
- [ ] Replace current CellBase-variation by the new CellBase-variation with updated frequencies

**Comment by j-coll** [comment]
We have found 141 pairs of duplicated variants due to a liftover to the same position. 
Example:

```
1	13497662	rs202124002	G	C	.	PASS	DBSNP=dbSNP_137;EA_AC=0,6844;AA_AC=61,3661;TAC=61,10505;MAF=0.0,1.6389,0.5773;GTS=CC,CG,GG;EA_GTC=0,0,3422;AA_GTC=3,55,1803;GTC=3,55,5225;DP=18;GL=PRAMEF16;CP=0.0;CG=-1.0;AA=G;CA=.;EXOME_CHIP=no;GWAS_PUBMED=.;FG=NM_001045480.1:missense;HGVS_CDNA_VAR=NM_001045480.1:c.959G>C;HGVS_PROTEIN_VAR=NM_001045480.1:p.(S320T);CDS_SIZES=NM_001045480.1:1425;GS=58;PH=benign:0.27;EA_AGE=.;AA_AGE=.;GRCh38_POSITION=1:13392036
1	13718496	rs371453768	G	C	.	PASS	DBSNP=dbSNP_138;EA_AC=1,5483;AA_AC=31,2259;TAC=32,7742;MAF=0.0182,1.3537,0.4116;GTS=CC,CG,GG;EA_GTC=0,1,2741;AA_GTC=2,27,1116;GTC=2,28,3857;DP=14;GL=PRAMEF17;CP=0.0;CG=-0.0;AA=G;CA=.;EXOME_CHIP=no;GWAS_PUBMED=.;FG=NM_001099851.1:missense;HGVS_CDNA_VAR=NM_001099851.1:c.959G>C;HGVS_PROTEIN_VAR=NM_001099851.1:p.(S320T);CDS_SIZES=NM_001099851.1:1425;GS=58;PH=benign:0.27;EA_AGE=.;AA_AGE=.;GRCh38_POSITION=1:13392036
```

We have excluded this variants.

There are also 536 variants that couldn't be mapped to the grch38.
Example:

```
1   1585597 rs7531938       A       G       .       PASS    DBSNP=dbSNP_116;EA_AC=5778,2338;AA_AC=1863,1773;TAC=7641,4111;MAF=28.8073,48.7624,34.9813;GTS=GG,GA,AA;EA_GTC=2085,1608,365;AA_GTC=495,873,450;GTC=2580,2481,815;DP=78;GL=CDK11B;CP=0.0;CG=-2.4;AA=A;CA=.;EXOME_CHIP=no;GWAS_PUBMED=.FG=NM_033493.1:intron,NM_033492.1:intron,NM_033489.1:intron,NM_033488.1:intron,NM_033487.1:intron,NM_033486.1:intron;HGVS_CDNA_VAR=NM_033493.1:c.231+1222T>C,NM_033492.1:c.231+1222T>C,NM_033489.1:c.138+365T>C,NM_033488.1:c.129+1222T>C,NM_033487.1:c.-8249T>C,NM_033486.1:c.240+365T>C;HGVS_PROTEIN_VAR=.,.,.,.,.,.;CDS_SIZES=NM_033493.1:2085,NM_033492.1:2112,NM_033489.1:1992,NM_033488.1:1983,NM_033487.1:1581,NM_033486.1:2094;GS=.,.,.,.,.,.;PH=.,.,.,.,.,.;EA_AGE=.;AA_AGE=.;GRCh38_POSITION=-1
```

**Comment by katherinesmith** [comment]
Thanks @j-coll. Given these findings and what we know about the different conversion methods, I believe that it would be preferable to use the Ensembl conversions rather than the official liftover.

**Comment by katherinesmith** [comment]
I've checked the Ensembl conversions and each of the two VCFs contains just two variants with identical CHROM, POS, REF and ALT:

1 13392427 CT  C
X 49553151 CGT C

**Comment by javild** [comment]
Oficial liftover was finally loaded. Can be revisited if needed
