### ISSUE TITLE
Protein Model, Region Model, featureClass are not working

### ISSUE THREAD

**Issue by wbari** [opencb/cellbase#326]
Hey @javild The following services are not working as intended :

- [x] http://bioinfodev.hpc.cam.ac.uk/cellbase-4.5.0-SNAPSHOT/webservices/rest/v4/hsapiens/feature/protein/model

Returns Null

- [x] http://bioinfodev.hpc.cam.ac.uk/cellbase-4.5.0-SNAPSHOT/webservices/rest/v4/hsapiens/genomic/region/model

Returns Null

- [x] http://bioinfodev.hpc.cam.ac.uk/cellbase-4.5.0-SNAPSHOT/webservices/rest/v4/hsapiens/regulatory/featureClass

Throws NullPointerException.

- [x] http://bioinfodev.hpc.cam.ac.uk/cellbase-4.5.0-SNAPSHOT/webservices/rest/v4/hsapiens/feature/variation/model?limit=-1&skip=-1&count=false&Output%20format=json

Return Null

- [x] http://bioinfodev.hpc.cam.ac.uk/cellbase-4.5.0-SNAPSHOT/webservices/rest/v4/hsapiens/regulation/tf/featureClass?limit=-1&skip=-1&count=false&Output%20format=json

Return Null if you don't provide a featureType. 

- [x] http://bioinfodev.hpc.cam.ac.uk/cellbase-4.5.0-SNAPSHOT/webservices/rest/v4/hsapiens/regulation/tf/featureClass?limit=-1&skip=-1&count=false&Output%20format=json

Returns  "error": "java.lang.NullPointerException",
Cause : If featureType is absent raise this error. 

These webservices work fine on http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v4/hsapiens/regulatory/featureClass

**Comment by javild** [comment]
Fixed. 

Some of them were actually due to a java-common-libs bug
https://github.com/opencb/java-common-libs/issues/32
