### ISSUE TITLE
Include 1000 Genomes Phase 3 mitochondrial allele frequencies (GRCh37)

### ISSUE THREAD

**Issue by katherinesmith** [opencb/cellbase#329]
http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chrMT.phase3_callmom-v0_4.20130502.genotypes.vcf.gz

Documentation at http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/README_chrMT_phase3_callmom.md

**Comment by javild** [comment]
Fixed
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v4/hsapiens/genomic/region/MT%3A1-10000/variation?limit=3&skip=-1&count=false&Output%20format=json&histogram=false&interval=200000&include=annotation.populationFrequencies
