### ISSUE TITLE
Use human reference Patches (GRCh37 and GRCh38)

### ISSUE THREAD

**Issue by mh11** [opencb/cellbase#332]
Just wondering if it is possible to use human reference patches for variant prediction in cell base?

e.g. [rs549446](http://www.ensembl.org/Homo_sapiens/Variation/Context?db=core;g=ENSG00000281879;r=CHR_HG2030_PATCH:133259650-133260404;t=ENST00000626615;v=rs549446;vdb=variation;vf=153775830)
CHR_HG2030_PATCH 133259982 C/T

The current query (if i put it correctly) doesn't seem return annotations:
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v4/hsapiens/genomic/variant/CHR_HG2030_PATCH:133259982:C:T/annotation?assembly=GRCh38

**Comment by javild** [comment]
Hi @mh11 
Only gencode annotated contigs are available by using accessions as provided by gencode. Check this list:
```
    "GL000008.2",
    "GL000009.2",
    "GL000194.1",
    "GL000195.1",
    "GL000205.2",
    "GL000213.1",
    "GL000216.2",
    "GL000218.1"
    "GL000219.1",
    "GL000220.1",
    "GL000224.1",
    "GL000225.1",
    "KI270442.1",
    "KI270706.1",
    "KI270707.1",
    "KI270708.1",
    "KI270711.1",
    "KI270713.1",
    "KI270714.1",
    "KI270721.1",
    "KI270722.1",
    "KI270723.1",
    "KI270724.1",
    "KI270726.1",
    "KI270727.1",
    "KI270728.1",
    "KI270731.1",
    "KI270733.1",
    "KI270734.1",
    "KI270741.1",
    "KI270743.1",
    "KI270744.1",
    "KI270750.1",
    "KI270752.1",
```

Examples:
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v4/hsapiens/genomic/variant/KI270711.1:11707:C:T/annotation?assembly=GRCh38
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v4/hsapiens/feature/gene/search?assembly=GRCh38&limit=3&region=KI270711.1:1-100000
