### ISSUE TITLE
meta & clinical cell base clients and also get method to query any rest end point  

### ISSUE THREAD

**Issue by indikaraj** [opencb/cellbase#345]
As discussed, Please provide followings
- Require Meta cell base client and clinical cell base client for accessing data exposed through the Rest layer
- Generic getter method to access any Rest api endpoint
- Require cell base data version and code version in meta URL response. Code version has already been provided

**Comment by javild** [comment]
Done.

https://github.com/opencb/cellbase/commit/c00bcedef338a0f2f91ccff293159db2cc16048e
https://github.com/opencb/cellbase/commit/1b00b15e7efdb25a9374ff8c9f8cf5b5cd782502
https://github.com/opencb/cellbase/commit/0cf474604baa975cddc4f0050642bb15b7cd2612
