### ISSUE TITLE
Integrate the Database of Genomics Variants in CellBase

### ISSUE THREAD

**Issue by cjohnson12** [opencb/cellbase#350]
Cellbase returns only the variant accession number from DGV and not the rest of the annotation with it as defined in Description:  chromosome, start, end, name (=DGV id), varType, pubMedId, method (we want to evaluate which ones are precise), sampleSize, observedGains, observedLosses

From 1 in 
https://cnfl.extge.co.uk/display/CEL/Feature+requirements%3A+new+annotation+sources+for+structural+variants

**Comment by javild** [comment]
Done.
https://github.com/opencb/cellbase/commit/91d06e09a7e64aac5b4495e1396c41d2518fc22d
