### ISSUE TITLE
Integrate Simple Tandem Repeats by TRF (UCSC) in CellBase

### ISSUE THREAD

**Issue by cjohnson12** [opencb/cellbase#351]
Please return "consensusSize" as well, as this can theoretically be different from the "period"

From 2 in:
https://cnfl.extge.co.uk/display/CEL/Feature+requirements%3A+new+annotation+sources+for+structural+variants

**Comment by javild** [comment]
Done.
https://github.com/opencb/cellbase/commit/8348123004d23855733b6c527643527684f7ab5b
