### ISSUE TITLE
Integrate Duplications of >1000 Bases of Non-RepeatMasked Sequence (UCSC) in CellBase

### ISSUE THREAD

**Issue by cjohnson12** [opencb/cellbase#352]
Fields "score" and "sequence" are not returned with the segmental duplication data as requested in description.

From 3 in:
https://cnfl.extge.co.uk/display/CEL/Feature+requirements%3A+new+annotation+sources+for+structural+variants

**Comment by javild** [comment]
Sorry @cjohnson12 this "issue" was incorrectly reported as commented at:
https://cnfl.extge.co.uk/display/CEL/Feature+requirements%3A+new+annotation+sources+for+structural+variants?focusedCommentId=67835630#comment-67835630

I'll close this ticket
