### ISSUE TITLE
Integrate WindowMasker track (UCSC) in CellBase

### ISSUE THREAD

**Issue by cjohnson12** [opencb/cellbase#353]
The field "name" is not returned together with the rest of the annotation fields as requested in Description.

From 4 in
https://cnfl.extge.co.uk/display/CEL/Feature+requirements%3A+new+annotation+sources+for+structural+variants

**Comment by javild** [comment]
Done.
https://github.com/opencb/cellbase/commit/8348123004d23855733b6c527643527684f7ab5b
