### ISSUE TITLE
Basic CellBase annotation for SVs and CNVs

### ISSUE THREAD

**Issue by cjohnson12** [opencb/cellbase#358]
Annotating TRANSLOCATIONS:
Data model for translocations doesn't really work. Issues:
1) Currently not possible to assign which chromosomal band relates to which breakpoint, as chromosome number is not a part of the chromosomal band annotation

From 2 in:
https://cnfl.extge.co.uk/display/CEL/Feature+Requirements%3A+Structural+Variants+and+CellBase

**Comment by javild** [comment]
Done.
https://github.com/opencb/cellbase/commit/7b2b3cd3153d265609d679c2c1b0237585d5d9a1
