### ISSUE TITLE
BUG: obsolete url returns 308 which makes wget fail

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/cellbase#361]
fetching [http://dgidb.genome.wustl.edu/downloads/interactions.tsv](http://dgidb.genome.wustl.edu/downloads/interactions.tsv) returns 308 Permanent Redirect which wget doesn't follow so it fails to download the file. 

```
$ wget --tries=10 http://dgidb.genome.wustl.edu/downloads/interactions.tsv -O ensembl/homo_sapiens_grch38/gene/geneDrug/dgidb.tsv
HTTP request sent, awaiting response... 308 Permanent Redirect
2017-09-26 09:02:09 ERROR 308: Permanent Redirect.
$ $ curl -v http://dgidb.genome.wustl.edu/downloads/interactions.tsv 
>
< HTTP/1.1 308 Permanent Redirect
< Location: http://www.dgidb.org/downloads/interactions.tsv
<
```

But the location returned http://www.dgidb.org/downloads/interactions.tsv is also invalid (404). Also the link on the [downloads page](http://www.dgidb.org/downloads/) - [http://www.dgidb.org/downloads/data/interactions.tsv](http://www.dgidb.org/downloads/data/interactions.tsv) returns 404. I'm writing them an email..

affected version: v4.5.0

**Comment by mbsimonovic** [comment]
UPDATE: they've fixed the url, more details [here](https://github.com/griffithlab/dgi-db/issues/294), the correct url is [http://dgidb.org/data/interactions.tsv](http://dgidb.org/data/interactions.tsv)

**Comment by javild** [comment]
Many thanks for this, @mbsimonovic 
I'll include the url fix in the new hotfix branch
