### ISSUE TITLE
Exception building human (ensembl r85) - error parsing MotifFeatures.gff

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/cellbase#362]
Affected version: develop and v4.5.0. 

call stack is: 
[addTranscriptTfbstoList() GeneParser.java#L626](https://github.com/opencb/cellbase/blob/v4.5.0/cellbase-app/src/main/java/org/opencb/cellbase/app/transform/GeneParser.java#L626)
[getTranscriptTfbses() GeneParser.java#L606](https://github.com/opencb/cellbase/blob/v4.5.0/cellbase-app/src/main/java/org/opencb/cellbase/app/transform/GeneParser.java#L606)
[parse() GeneParser.java#L204](https://github.com/opencb/cellbase/blob/v4.5.0/cellbase-app/src/main/java/org/opencb/cellbase/app/transform/GeneParser.java#L204)

The offending line is
```java
        String[] tfbsNameFields = tfbs.getAttribute().split("=")[1].split(":");
        transcriptTfbses.add(new TranscriptTfbs(tfbsNameFields[0], tfbsNameFields[1], chromosome, tfbs.getStart(), tfbs.getEnd(),
                tfbs.getStrand(), getRelativeTranscriptTfbsStart(tfbs, transcript), getRelativeTranscriptTfbsEnd(tfbs, transcript),
                Float.parseFloat(tfbs.getScore())));
```
tfbs comes from [MotifFeatures.gff.gz](ftp://ftp.ensembl.org/pub/release-85/regulation/homo_sapiens/MotifFeatures.gff.gz):

```
14      .       TF_binding_site 23034888        23034896        7.391   -       .       binding_matrix=MA0597.1;motif_feature_type=THAP1
...
```

 `tfbs.getAttribute()` returns `binding_matrix=MA0341.1;motif_feature_type=Egr1` so after two split() calls, it returns an array of size 1, and then the following line `tfbsNameFields[1]` throws IndexOutOfBounds. Looks like it should split on ';' not on ':'? 

The same applies to [mouse MotifFeatures](ftp://ftp.ensembl.org/pub/release-85/regulation/mus_musculus/MotifFeatures.gff.gz).

**Comment by mbsimonovic** [comment]
Looking at the [release-84/mus_musculus/MotifFeatures.gff.gz](ftp://ftp.ensembl.org/pub/release-84/regulation/mus_musculus/MotifFeatures.gff.gz):

```
chr10   RegulatoryBuild TFBS Motifs v12.0       TF_binding_site 3108122 3108140 9.424   -       .       Name=CTCF:MA0139.1
```
seems like they changed the format in r85, it used to be a colon.

**Comment by mbsimonovic** [comment]
[GFF3 defines](http://gmod.org/wiki/GFF3#GFF3_Format) the attribute field as: `A list of feature attributes in the format tag=value.`

**Comment by mbsimonovic** [comment]
Looking at the mouse and human MotifFeatures.gff files, they all have the same format: `binding_matrix=???;motif_feature_type=???`, so it can be parsed easily with a simple regex:

```java
        final Pattern p = Pattern.compile("binding_matrix=(.+);motif_feature_type=(.+)");
        final Matcher matcher = p.matcher(tfbs.getAttribute());
        if (!matcher.matches()) {
            logger.error("failed to parse MotifFeatyres: " + tfbs.getAttribute());
            return (ArrayList<TranscriptTfbs>) Collections.EMPTY_LIST;
        }

        transcriptTfbses.add(new TranscriptTfbs(matcher.group(2), matcher.group(1), chromosome, tfbs.getStart(), tfbs.getEnd(),
                tfbs.getStrand(), getRelativeTranscriptTfbsStart(tfbs, transcript), getRelativeTranscriptTfbsEnd(tfbs, transcript),
                Float.parseFloat(tfbs.getScore())));
```

**Comment by javild** [comment]
Thanks for your comment.
We have tested the code with e89 data and should be running. I'll have a look at this issue and check if we missed something

**Comment by javild** [comment]
Hi @mbsimonovic 

I've been reviewing this issue. At some point ENSEMBL changed the way they distribute regulatory data (don't remember now the version, somewhere between 83 and 89). We adapted the code accordingly and now these two files are downloaded:

_Mus musculus_
ftp://ftp.ensembl.org/pub/release-90/regulation/mus_musculus/mus_musculus.GRCm38.Regulatory_Build.regulatory_features.20161111.gff.gz
ftp://ftp.ensembl.org/pub/release-90/regulation/mus_musculus/mus_musculus.GRCm38.motiffeatures.20161111.gff.gz

_Homo sapiens_
ftp://ftp.ensembl.org/pub/release-90/regulation/homo_sapiens/homo_sapiens.GRCh38.Regulatory_Build.regulatory_features.20161111.gff.gz
ftp://ftp.ensembl.org/pub/release-90/regulation/homo_sapiens/homo_sapiens.GRCh38.motiffeatures.20161111.gff.gz

Previous files (i.e. MotifFeatures.gff.gz) are no longer provided by ENSEMBL and the implemented parser may indeed not be able to deal with them.

Some deprecated code has been maintained there for legacy issues but will soon be removed, for example:
https://github.com/opencb/cellbase/blob/v4.5.0/cellbase-app/src/main/java/org/opencb/cellbase/app/cli/DownloadCommandExecutor.java#L646
https://github.com/opencb/cellbase/blob/v4.5.0/cellbase-app/src/main/java/org/opencb/cellbase/app/transform/RegulatoryRegionParser.java#L72

Finally, we strongly advise to upgrade to 4.5.3.

Please, let us know if you find any other problem

**Comment by mbsimonovic** [comment]
just tried with v4.5.4 and ensembl r90 and it works ok, so i'm gonna close the issue, thanks!
