### ISSUE TITLE
How to setup the project?

### ISSUE THREAD

**Issue by renyaoxiang** [opencb/cellbase#367]
We would like to having a project to support the ga4gh schema datas.
It seems the project Cellbase is rightly the one we are searching.
The project can convert the kinds of bioinfomation files to the ga4gh schema datas , does it?
Now how could we setup and start a test?

**Comment by javild** [comment]
Dear @renyaoxiang 

Thank you for comment and your interest in the CellBase project.

Could you please provide some more details about your use case to help you understand how CellBase can be of use to you?

CellBase implements an API to a NoSQL database that integrates core biological annotation. Please, find more documentation at http://docs.opencb.org/display/cellbase
You can finde detailed documentation on how to build CellBase database at
http://docs.opencb.org/display/cellbase/Building+the+CellBase+database
and some documentation on how to build and install the code at
https://github.com/opencb/cellbase/blob/develop/README.md

In principle, CellBase does not include any particular implementation of GA4GH data models. Actually GA4GH models, in particular variation and variant annotation models, are currently being revisited and redesigned.

Please, let us know if we can be of any further help.

**Comment by renyaoxiang** [comment]
Dear @javild 
Thank you for your answer.

Another answer, the following info is very important for us, and if I could have more details, such as  official declaration doc or the effect of the schema change. We may reevaluate our plan.
```
Actually GA4GH models, in particular variation and variant annotation models, are currently being revisited and redesigned.
```

**Comment by javild** [comment]
Dear @renyaoxiang 

I do not really know the details of the service you need. There is a plan for CellBase to support GA4GH schemas but it has not had the highest priority so far.

The GA4GH Genomic Knowledge Standards workstream is currently working on variant and variant annotation representation based on the Variation Modelling Collaboration (VMC) work
https://www.ga4gh.org/howwework/workstreams/genomic-knowledge-vision-statement.html
https://github.com/ga4gh/vmc

**Comment by renyaoxiang** [comment]
@javild 
Thank you!
