### ISSUE TITLE
Asterix in variant throws 500 error

### ISSUE THREAD

**Issue by nicholsn** [opencb/cellbase#369]
I have a local install of cellbase-4.5.1 where I get a 500 response with an error of `java.lang.NullPointerException` when an asterix is present indicating an alt. However, if I make this same call to the public cellbase at http://bioinfo.hpc.cam.ac.uk doesn't have an issues.

Curl Call
```
curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" -d "1:908963:ATCGGGGTCAGGCCCCCGGGCGCACCTTTGCTGGTATATGCGGGGGTCGGGGTCAGGCCCCCGGGCGCACCGTTGCTGGTATATGCGGGGGTCGGGGTCAGGCCCCCGGGCGCACCGTTGCTGGTATATGCGGTGGTCGGGGTCAGGCCCCCCGGGCGCACTGTTGCTGGTATATGCGGTGG:*" "http://hostname:8080/cellbase-4.5.1/webservices/rest/v4/hsapiens/genomic/variant/annotation?assembly=GRCh38&limit=-1&skip=-1&skipCount=false&count=false&Output%20format=json&normalize=false&phased=false&useCache=false&imprecise=true&svExtraPadding=0&cnvExtraPadding=0"
```

Response
```
{"apiVersion":"v4","warning":"","error":"java.lang.NullPointerException","queryOptions":{"exclude":["_id","_chunkIds"],"metadata":true,"include":null,"limit":1000,"skip":-1,"skipCount":false,"count":false},"response":[{"id":"","dbTime":-1,"numResults":-1,"numTotalResults":-1,"warningMsg":"Future errors will ONLY be shown in the QueryResponse body","errorMsg":"DEPRECATED: java.lang.NullPointerException","resultType":"","result":[]}]}
```

Any thoughts on what the issue may be?

**Comment by javild** [comment]
Hi @nicholsn , thanks for your message

The fact that works when pointed to bioinfo.hpc.cam.ac.uk sounds weird to me. We found an issue in 4.5.1 which had to do with the server not being able to parse certain complex variants or special characters such as the * which, in turn, made the client raise an Exception like the one you re reporting. We implemented a non-perfect solution for that in 4.5.3 which essentially will raise a warning, skip variants that cannot be parsed and continue the annotation run until the end.

Can you please update (both server and client) to the 4.5.3 and try again?
https://github.com/opencb/cellbase/releases

**Comment by nicholsn** [comment]
Hey @javild, I haven't had a chance  to update to 4.5.3 yet but can confirm that in 4.5.1 the error is caught when using the cellbase_db_adaptor rather than REST.

```
2017-12-01 07:11:34 [pool-2-thread-8] ERROR VariantAnnotationCalculator:517 - Consequence type was not calculated for variant 2:2004259:GTTCTTTCCTGCAGGCGTTCTTTCCTGCATGCGTTCTTTCCTGCATGCGTTCTTTCCTGCAGGCGTTCTTTCCTGCATACGTTCTTTCCTGCGTGCCTTCTTTCCTGTGTGCC:*. Unrecognised variant format. Leaving an empty consequence type list.
``` 

For reference, it looks like the `*` is a new character in VCF 4.2 specification that stands for a deleted allele and is output by GATK - see https://gatkforums.broadinstitute.org/gatk/discussion/5904/asterisk-in-the-alt-feild-of-vcf

I'll upgrade and check back...

**Comment by javild** [comment]
@nicholsn thanks for the info. Yes, we are aware of that and it's something we must improve.

I've been thinking about it and double checking. I'm pretty sure the issue will resolve as soon as you upgrade both client and server to 4.5.3. You're not getting the error when pointing to bioinfo.hpc.cam.ac.uk because this server is already running 4.5.3:
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v4/meta/about

Please, upgrade and let us know if you find any issue

**Comment by nicholsn** [comment]
great, I can confirm this is working now - thanks!
