### ISSUE TITLE
New DisGeNET data source to be included

### ISSUE THREAD

**Issue by imedina** [opencb/cellbase#39]
DisGeNET database need to be downloaded and included:

http://www.disgenet.org/web/DisGeNET/v2.1

A new collection gene_disease_association must be created.

**Comment by imedina** [comment]
This should be kept in a different collection, a possible name could be 'gene_disease_association'.

**Comment by javild** [comment]
Disgenet data can now be downloaded with the "download" command and "-d gene2disease" option. Working on Disgenet parser

**Comment by imedina** [comment]
This could be replaced by #138, moved to Under consideration
