### ISSUE TITLE
Add support for database configuration using environment variables

### ISSUE THREAD

**Issue by marrobi** [opencb/cellbase#395]
At present `configuration.json` needs to be edited to configure database connectivity. 

When dealing with multiple front end web servers this means multiple files need to be edited or mounted in from a central location.

This process would be much easier if environment variables were supported for database configuration. Especially when using docker images as they can be passed in when starting a container and it is not appropriate to create a new custom image for each deployment. 

For our immediate needs the mongodb host, user, pass, and options, including SSL are required.

cc @imedina @j-coll

**Comment by j-coll** [comment]
- CELLBASE_DATABASES_MONGODB_HOST
- CELLBASE_DATABASES_MONGODB_USER
- CELLBASE_DATABASES_MONGODB_PASSWORD
- CELLBASE_DATABASES_MONGODB_OPTIONS_*
   - CELLBASE_DATABASES_MONGODB_OPTIONS_AUTHENTICATION_DATABASE
   - CELLBASE_DATABASES_MONGODB_OPTIONS_REPLICA_SET
   - CELLBASE_DATABASES_MONGODB_OPTIONS_READ_PREFERENCE
   - CELLBASE_DATABASES_MONGODB_OPTIONS_CONNECTIONS_PER_HOST
   - CELLBASE_DATABASES_MONGODB_OPTIONS_SSL_ENABLED

**Comment by marrobi** [comment]
Will give it a go Monday. Can the SSL fix be merged - otherwise will have to merge a couple of branches together. Thanks!

**Comment by marrobi** [comment]
Will give it a go Monday. Can the SSL fix be merged - otherwise will have to merge a couple of branches together. Thanks!

**Comment by j-coll** [comment]
Everything merged now, I'll close both issues

**Comment by Lucioric2000** [comment]
that environmental variables need is not specified in the installation information, so that new users that install cellbase following the instructions encounter errors when trying to run the load command. Is there any way to include default values for the users that don't want to specify them in environment variables?.

**Comment by j-coll** [comment]
Hi @Lucioric2000 

These environmental variables should not be required for the installation, as long as the `configuration.json` file is configured properly. Please, let me know if this is not correct.

To configure cellbase, you can manually edit the `configuration.json` file, or use the maven properties, as specified here: [Build](https://github.com/opencb/cellbase#build).

I agree that these optional env-vars should be documented in the main README.md, and in the [Cellbase Documentation](http://docs.opencb.org/display/cellbase).

Regarding the default values, if you compile cellbase without any maven profile, it will be configured to connect to an unsecured mongodb instance in `localhost:27017`

**Comment by Lucioric2000** [comment]
For installation, these are not required, but errors are raised when running cellbase load

**Comment by j-coll** [comment]
Thanks for reporting this.
Was the error happening before this modification?
Could you please reproduce the error adding `--log-level debug` to the CLI, and copy here the command and output?
Also, could you copy the `configuration.json` file. Did you made any manual modification to the file after the compilation?
