### ISSUE TITLE
Default memory is set to be 16GB, which causes memory errors

### ISSUE THREAD

**Issue by julie-sullivan** [opencb/cellbase#450]
I can run a build of cellbase if I lower that value, e.g. to 5GB:

https://github.com/opencb/cellbase/blob/develop/cellbase-app/pom.xml#L88

**Comment by imedina** [comment]
Variant builder needs 16GB to run. In any case, Xmx is the max memory is going to use, it should not take more than 5GB if not needed

**Comment by julie-sullivan** [comment]
This is what I get when i try to build with my 8 GB laptop:

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x000000070d400000, 564658176, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 564658176 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/julie/git/cellbase/hs_err_pid32506.log
```

Running this command
```
./build/bin/cellbase-admin.sh build --assembly GRCh37 --common /tmp/ --data gene --output /tmp/ --species hsapiens -i /tmp/homo_sapiens_grch37/
```

I didn't have this issue on the macbook, and I don't have the issue when I change the `mx` value to be lower. I can also build (sometimes) if I am not running anything else, e.g. slack and firefox.
