### ISSUE TITLE
Add new step to publish Python package to PyPI

### ISSUE THREAD

**Issue by julie-sullivan** [opencb/cellbase#505]
See #493 

- [x] Add a new workflow that publishes to pypi. Password is a secrety. Version comes the setup file. Not able to test! Just guess.
- [x] Also, move python and R clients next to Java client.

**Comment by julie-sullivan** [comment]
https://packaging.python.org/tutorials/packaging-projects/

**Comment by imedina** [comment]
Will this include the development of a shell script to build and push PyPI packages?

**Comment by imedina** [comment]
There is a test PyPI server which is very convenient! :-)

https://test.pypi.org/project/pyopencga/
