### ISSUE TITLE
Fixes for ExonWSServer

### ISSUE THREAD

**Issue by mbleda** [opencb/cellbase#53]
The following Exon WS should be implemented (currently not working):
* `/{version}/{species}/feature/exon/{exonId}/info`
* `/{version}/{species}/feature/exon/{exonId}/region`
* `/{version}/{species}/feature/exon/{exonId}/sequence`
* `/{version}/{species}/feature/exon/{exonId}/transcript`

Interesting but not urgent:
* `/{version}/{species}/feature/exon/{exonId}/aminos`

`/{version}/{species}/feature/exon/{exonId}/bysnp` should not be there and has been marked as Deprecated.

**Comment by imedina** [comment]
The following two web services:
* `/{version}/{species}/feature/exon/{exonId}/region`
* `/{version}/{species}/feature/exon/{exonId}/sequence`

should be implemented using _include_ and _exclude_ query params, ie.:
`...?include=region`

**Comment by mbleda** [comment]
Since we are going to implement _include_ and _exclude_ query params, the suggested WS do no longer make sense. I suggest to close this issue.

**Comment by imedina** [comment]
I agree, is marked as Deprecated and deleted in next release
