### ISSUE TITLE
Fixes for SnpWSServer

### ISSUE THREAD

**Issue by mbleda** [opencb/cellbase#54]
The following SNP WS should be implemented (currently not working):
* `/{version}/{species}/feature/snp/{snpId}/consequence_type`
* `/{version}/{species}/feature/snp/{snpId}/population_frequency`
* `/{version}/{species}/feature/snp/{snpId}/xref`

Interesting but not urgent:
* `/{version}/{species}/feature/snp/{snpId}/sequence`
* `/{version}/{species}/feature/snp/{snpId}/regulatory`

List of deprecated WS:
* `/{version}/{species}/feature/snp/{snpId}/consequence_types`
* `/{version}/{species}/feature/snp/{snpId}/phenotypes`

**Comment by imedina** [comment]
These two web services need to be implemented:
* /{version}/{species}/feature/snp/{snpId}/consequence_types
* /{version}/{species}/feature/snp/{snpId}/phenotypes ==> clinical

**Comment by imedina** [comment]
A new WS with no SNP id has been implemented:

.../feature/snp/consequence_types

Also a new WS in Gene to fetch SNPs has been implemented:

.../feature/gene/BRCA2/snp?offset=2000

The ones proposed are available using exclude/include modifiers.
