### ISSUE TITLE
Fixes for GeneWSServer

### ISSUE THREAD

**Issue by mbleda** [opencb/cellbase#55]
The following Exon WS should be implemented (currently not working):
* `/{version}/{species}/feature/gene/{geneId}/tfbs`
* `/{version}/{species}/feature/gene/{geneId}/mirna_target`
* `/{version}/{species}/feature/gene/{geneId}/reactome`

`/{version}/{species}/feature/gene/{geneId}/protein` returns the PPIs for the specified gene. We should rename this WS to `ppi` or `protein_interaction`.

Would be also interesting to create a proper `/{version}/{species}/feature/gene/{geneId}/protein` WS returning UniProt information for this gene.

**Comment by imedina** [comment]
Agree. These and others WS are being implemented
