### ISSUE TITLE
Cellbase public endpoint?

### ISSUE THREAD

**Issue by ameintjes** [opencb/cellbase#600]
My annotate command is failing with a 404 not found for http://bioinfo.hpc.cam.ac.uk/cellbase. Via browser the url also reports 404 and the host http://bioinfo.hpc.cam.ac.uk/ lists under construction.

Has the url having changed? Don't see mention of that in github but I may have missed it

**Comment by imedina** [comment]
Hi @ameintjes,

Sorry about the lack of information, we are putting together the new documentation and the new release notes.

Please for CellBase 5.x (only GRCh38) you should use now the domain under Zetta Genomics (start-up created from OpenCB):

https://ws.zettagenomics.com/cellbase

One example:
https://ws.zettagenomics.com/cellbase/webservices/rest/v5.1/hsapiens/genomic/variant/1:230710048:A:G/annotation

Sorry again for the inconvenience.

**Comment by ameintjes** [comment]
Thanks Ignacio, I will try this solution
