### ISSUE TITLE
QueryOptions functionality to be enabled in the variant annotation WS

### ISSUE THREAD

**Issue by javild** [opencb/cellbase#69]
Several functionalities are required.

Filters:
* geneset=gencode_basic: must only annotate against genecode-basic genes. Genecode-basic genes can be identified by looking at the gencode gtf:

ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz

There is a tag="basic" for each gencode-basic transcript. Tasks:
  1.- gencode gtf has to be downloaded
  2.- The list of gencode-basic transcript ids (ENSTxxx) must be loaded within the GeneParser into a HashSet.
  3.- GeneParser will include a new annotationFlag "basic" for all parsed genecode-basic transcripts
  4.- getAllConsequenceTypesByVariantList at VariantAnnotationMongoDBAdaptor will check that flag before proceeding to annotate the variant

* so=term1,term2,term3: getAnnotationByVariantList shall only return the annotation for those variants which present any of these so terms.

Includes:

* include={variation,clinical,consequence,conservation}: to allow enabling only certain annotation types.

**Comment by imedina** [comment]
What is the status of this?

**Comment by javild** [comment]
Following tags can be used for the include/exclude parameter:

variation,clinical,conservation,functionalScore,consequenceType,expression,geneDisease, drugInteraction,populationFrequencies
