### ISSUE TITLE
Allow loading of a cusmotized trait->EFO term mapping

### ISSUE THREAD

**Issue by javild** [opencb/cellbase#73]
Once issue #72 is solved, it shall be allowed to load into cellbase a list of mappings traitName->EFO term so that anyone can query by those trait names and get the corresponding EFO terms

**Comment by javild** [comment]
In a second review it was decided that loading the whole EFO into CellBase does not make much sense:
- EFO is currently just needed to provide appropriate trait->EFO mapping for ClinVar records, required for EVA clinical tab
- We do not find any more use cases of EFO at this moment nor in a near future

EVA requirement will be solved by adding value to the clinical collection: adding trait-EFO mappings to each ClinVar document

**Comment by pabarcgar** [comment]
Implemented in the clinvar parser. 

It takes a file with a mapping between the clinvar preferred trait name and an EFO term id, its name and an URL (like this: http://purl.obolibrary.org/obo/HP_0000110). This file covers around 65% of the clinvar preferred trait names. For each clinvar record, it looks for a associated EFO term in the file, and if it exist, it adds three new traits names to the clinvar trait: EFO Id, EFO Name and EFO URL. Like EVA clinical tab is searching using clinvar trait names, you can enter an EFO id or name in the EVA "Trait Search" and the variants with this term will be returned, so no changes to the clinvar WS are needed.

The clinvar trait - EFO mapping file needs to be uploaded to the cellbase FTP server and added to the configuration file and the download executor.
