### ISSUE TITLE
Reference position in CLI

### ISSUE THREAD

**Issue by Antonior26** [opencb/cellbase#76]
CLI should skip reference position inestead of annotate them

**Comment by imedina** [comment]
Is this intended for gVCF where non-variants positions are reported?

**Comment by Antonior26** [comment]
Yes. Furthermore there are others vcf files, (not gVCF files) with
reference positions - i.e, vcf files from GATK -allsites from a WES BAM.

2015-04-07 11:47 GMT+01:00 Nacho <notifications@github.com>:
