### ISSUE TITLE
Return a list of diseases from 'clinical'

### ISSUE THREAD

**Issue by aaleman** [opencb/cellbase#82]
It would be great if Cellbase could have a WS for retrieving all the stored diseases (and associated genes). 
Maybe this WS could receive a query/path params to return only one (multiple) disease (s).

In this URL you have an example of the old version. 
http://ws-beta.bioinfo.cipf.es/cellbase/rest/v3/hsapiens/feature/snp/phenotypes

**Comment by javild** [comment]
Done:

http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/clinical/phenotype-gene
http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/clinical/phenotype-gene?include=clinvar
http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/clinical/phenotype-gene?include=gwas
