### ISSUE TITLE
strand is always set to null in full_annotation

### ISSUE THREAD

**Issue by Antonior26** [opencb/cellbase#83]

**Comment by imedina** [comment]
This is an example:

http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/variant/19:45411941:T:C/full_annotation

**Comment by imedina** [comment]
A fix has been implemented and it is running in beta server:

http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/variant/19:45411941:T:C/full_annotation
