### ISSUE TITLE
WS to query biotypes fails

### ISSUE THREAD

**Issue by javild** [opencb/cellbase#91]
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/gene/biotypes

Returns null

**Comment by imedina** [comment]
I would have been surprised otherwise:

https://github.com/opencb/cellbase/blob/develop/cellbase-mongodb/src/main/java/org/opencb/cellbase/mongodb/db/GeneMongoDBAdaptor.java#L139

**Comment by imedina** [comment]
New implementation using 'datastore' is done. This can be seen here:

http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/gene/biotypes

A filter by chromsome has been added:

http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/gene/biotypes?chromosome=21
