### ISSUE TITLE
MongoDB Loader log message for index building

### ISSUE THREAD

**Issue by pabarcgar** [opencb/cellbase#93]
A log message is needed when executing loader to show that the index is being built, because now you don't now what the program is doing after loading all documents. Example:

[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 63677 records read from 'model/gene.json.gz'
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - All the '63677' records have been loaded into the database
[main] INFO org.opencb.datastore.mongodb.MongoDataStore - MongoDataStore: connection closed

**Comment by javild** [comment]
Done.
