### ISSUE TITLE
Could have we the versions used in cellbase (ensembl, etc..) in variant annotation response?

### ISSUE THREAD

**Issue by Antonior26** [opencb/cellbase#96]
It will be very convenient in production pipelines. Just to make sure against what we are annotating today or check against what we annotated one year ago....

**Comment by imedina** [comment]
Returning that information in each of the annotations will make data to increase significantly. My proposal is to have one or more web services to return that information.

**Comment by javild** [comment]
Yes. Already agreed on this with Antonio. A small metadata file shall be created when annotating by using the CLI that stores all versions information.

**Comment by javild** [comment]
Moved to 4.0

**Comment by mattdmem** [comment]
This would be very useful - will this be implemented soon?

**Comment by javild** [comment]
Agree. You can access a good proxy to this with this web service
http://bioinfodev.hpc.cam.ac.uk/cellbase-dev-v4.0/webservices/rest/v4/meta/versions
Needs to be improved

**Comment by Antonior26** [comment]
That is cool, but doesn't contains the versions, which is what we need

**Comment by javild** [comment]
Done. The web service has been improved and now returns the data base source name, version and URLs from which all CellBase data were downloaded together with the date the data were downloaded.
