### ISSUE TITLE
[server] genomic region tfbs not working

### ISSUE THREAD

**Issue by frasator** [opencb/cellbase#97]
Can be tested using this url:
https://www.ebi.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/region/13:32850000-32899999/tfbs?of=json

**Comment by imedina** [comment]
That's not the correct CellBase host to use, remember it is installed at UCam, please do not use EBI any more:

http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/region/13:32850000-32899999/tfbs

That web services is in 'bioinfodev'. Please ise this host for development software:

http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/region/13:32850000-32899999/tfbs
