### ISSUE TITLE
Integrate DGIdb into CellBase

### ISSUE THREAD

**Issue by javild** [opencb/cellbase#99]
Implement download, parsing, loading and corresponding WSs for DGIdb

http://dgidb.genome.wustl.edu/

**Comment by imedina** [comment]
This could be integrated into 'gene' collection, right?

**Comment by javild** [comment]
Yes. The "build" command for the gene data command must be modified to integrate DGIdb information within the gene jsons. Thus, there is actually no need to implement a "load" command for DGIdb itself.

**Comment by javild** [comment]
DGIdb is now integrated within the Gene documents. Drug-gene interactions are also returned by the variant annotation web service:

http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/variant/19:45411941:T:C/full_annotation

**Comment by javild** [comment]
It would be nice to implement filters that provide lists of genes filtering by drug and lists of drugs filtering by gene
